### ISSUE TITLE
Downloaded Mining software does not disclose the 2% mining fee

### ISSUE THREAD

**Issue by mreid2005** [vertcoin/One-Click-Miner#19]
Transparency is key. 

1. make sure that users see the License before using the one-click miner. give Attribution for third-party binaries or sources that are being used.

2. Disclose FEES!

**Comment by patchandthat** [comment]
This has been on my mind as well and I agree. Finding out by surprise is not a nice user experience at all.

I've been thinking that a tutorial/wizard style interface the first time OCM is run would be beneficial.  This can cover the above, but also talk about how to set up, the benefits of running your own node, and why it's preferable to mine to a full wallet rather than SPV/electrum.

I think it may also be worthwhile as a feature to communicate what % efficiency gains they can expect get from using vertminer over ccminer, but allow the user to opt out and use ccminer if they wish.

**Comment by zemrys** [comment]
This will be addressed in the next update. 
@patchandthat That's a good idea and what I had originally planned for the OCM, but it got some backlash when I presented the idea to the community.  I guess people like "one-click" to be a literal interpretation.
