### ISSUE TITLE
Access to the path 'ocm_vertminer.exe' is denined

### ISSUE THREAD

**Issue by o-Epictetus-o** [vertcoin/One-Click-Miner#22]
Access to the path 'ocm_vertminer.exe' is denined is shown when Update Available is clicked then Update found for Nvidia Miner! Click OK to download is clicked. Version 1.1.6.0

I also noticed that when I went to AppData, Roaming there is no folder for OCM or anything else.

**Comment by zemrys** [comment]
This is due to the issue addressed [here](https://github.com/vertcoin/One-Click-Miner/issues/8).  The directory containing the OCM's miners/configs can be found in ..\Documents\Vertcoin One-Click Miner. You will need to add an exception to your security software(s) for the OCM and that directory to prevent what you are seeing.  Closing due to issue already being open [#8](https://github.com/vertcoin/One-Click-Miner/issues/8).

**Comment by o-Epictetus-o** [comment]
Stupid macafee....time to build a mining setup :-)
