### ISSUE TITLE
OCM Failing to Update

### ISSUE THREAD

**Issue by DandelionAcres** [vertcoin/One-Click-Miner#23]
When starting OCM, receive notice of "update found".  Update begins download then fails "an issue occurred during the download".  Happens every time, even with fresh instance launched and AV turned off.  This is for the Nvidia version.  Version is 1.1.6

**Comment by zemrys** [comment]
This is due to the issue addressed [here](https://github.com/vertcoin/One-Click-Miner/issues/8). The directory containing the OCM's miners/configs can be found in ..\Documents\Vertcoin One-Click Miner. You will need to add an exception to your security software(s) for the OCM and that directory to prevent what you are seeing. Closing due to issue already being open [#8](https://github.com/vertcoin/One-Click-Miner/issues/8).
