### ISSUE TITLE
Hosting fee %

### ISSUE THREAD

**Issue by Nubzorx** [vertcoin/One-Click-Miner#25]
So i setup everything, put in my 1% fee, I have people mining and haven't received anything yet.  Is there something missing, does it not work?  Or I am just a huge noobzor

**Comment by Sufuninja** [comment]
I assume that your are mining on P2Pool. To better understand how payouts work, go [here](http://p2pool.org/learn/index.php). It all revolves around 'shares'. If 1% of the miners work on your node doesn't equal a share, you will not receive a payment when a block is found.  The more time your node is up and the faster your connection is to others on the same network, the more miners you will attract. 
This isn't due to the One-Click-Miner but P2Pool's rules.
