### ISSUE TITLE
Reads as a trojan /after/ install.

### ISSUE THREAD

**Issue by paynode** [vertcoin/One-Click-Miner#42]
real or not, just sharing my experience...

after installing and attempting to run the miner, it let me know there was an update for CPU, would i like to download it...  Sure.  then malwarebytes pops up and lets me know that ocm_cpuminer.exe is infected with Trojan.BitCoinMiner.  When running the nvidia selection there is also an update, though it does not seem to piss off malwarebytes.
 
As I said, i can't tell if it's real, just a cautionary tale...

**Comment by zemrys** [comment]
This is a known issue.  Miner software is often considered malware by virus scanners/firewalls because they have been known to be used maliciously in the past.  In the OCM's case it is a false positive, but it can also prevent the OCM from downloading the miner software, so we recommend making an exception in your security software for the OCM to prevent that.

**Comment by paynode** [comment]
Understood.  It was just a weird situation, and no way to know if an exception is the safe thing to do.

Thanks for the response,
