### ISSUE TITLE
Virus detected when downloading Beta 1.1.5

### ISSUE THREAD

**Issue by aleybovich** [vertcoin/One-Click-Miner#8]
I just downloaded OCM 1.1.5 and Chrome showed a Virus warning

![image](https://user-images.githubusercontent.com/600721/31801886-f8ff1428-b518-11e7-9f3c-9e4593f79b98.png)

**Comment by zemrys** [comment]
This is a known issue.  The OCM automates the download of known miner software that is flagged by most virus scanners/firewalls as malware because they have been known to be used as such in the past.

**Comment by aleybovich** [comment]
So how do I download it if both IE and Chrome reject it?

**Comment by aleybovich** [comment]
Ok, I ended up using Powershell: 

`PS C:\Users\user> Invoke-WebRequest -Uri https://github.com/vertcoin/One-Click-Miner/releases/download/1.1.5/Vertcoin
OneClickMinerSetup.msi -OutFile .\Desktop\Installer.msi`

**Comment by BobbyGR** [comment]
It is possible the issue it's raising is the use of the injection to the registry for the autostart.  Not 100% but looking over it that's the only thing I can find where I would imagine it would have a red flag.  Maybe zemrys knows more about why. (maybe it's just because it's mining software in general)  And if possible we can adjust that?  Seems to be a red flag for everyone who get's OCM.

**Comment by patchandthat** [comment]
Yes, this is a big issue imo, especially if we want to position this software as an easy way to onboard new folks.

I don't think the autostart registry key is the issue, plenty of apps use that.

I would suggest getting a cert issued to sign the binaries, so that the msi and executables don't appear to be from an unknown publisher (this applies to all VTC related apps). I believe this is one of the most important things we should do, as we're routinely telling users to ignore a false positive, when we can't be sure that the files on the user's machine haven't been tampered with.  

We're targeting a user base with minimal technical knowledge, so even though there are hashes available, I think it's unrealistic to expect them all to calculate and verify the hashes on all software they intend to run.  Users who would do this would most likely just run ccminer themselves.

I've decompiled the msi, there's nothing in there that should set windows defender off as far as I can see.

We do have a lot of hard-coded strings which relate to mining software, ie. process names, executable and config file names.  Would be a good move to decouple this and see if that sorts it out.

Failing the above, we can submit to Microsoft for analysis, so that they can mark this as a false positive. https://www.microsoft.com/en-us/wdsi/filesubmission 
Evaluation criteria: https://www.microsoft.com/en-us/wdsi/antimalware-support/malware-and-unwanted-software-evaluation-criteria

**Comment by zemrys** [comment]
The hashes are intended as a verification for BETA users, not an end-all.  I am planning on signing all releases post beta.

The red flags from virus scanners/firewalls are likely due to the strings used to directly call and download the various miners.  On top of that, the miners should probably be recompiled under different names to attempt to circumvent their individual detection from scanners/firewalls.

Nothing should be submitted to Microsoft until this is ready for a full public release, code can change quickly in open beta, nullifying any previous submissions to Microsoft.

**Comment by KoenPeijnenborg** [comment]
Hello everyone,

Since my original query was closed, could someone explain in laymen's terms what I should do about the error: "Cannot access machine, pad or files. It is possible you do not have the correct clearance level."
As far as I know this is not due to the virus scanner, as I've made an exception for VTC OCM in there. I am administrator. I tried to find an answer to this question in other posts @zemrys referred me to, however I couldn't the information in these posts to solve my problem. Any help is greatly appreciated!!

**Comment by zemrys** [comment]
@KoenPeijnenborg Please come to our [Discord](https://discordapp.com/invite/vertcoin) and join either the #tech-support or #oneclick channel for direct support with your issue. It is likely still being caused by a security factor and will be much easier to troubleshoot in chat.
