### ISSUE TITLE
Beta 1.1.7.9: states update available and mining (cpu or AMD) says download available then fails.

### ISSUE THREAD

**Issue by sohosynergy** [vertcoin/One-Click-Miner#84]
I have tried all of your betas up to and including 1.1.7.9.  Each version does successfully download the next version until we hit 1.1.7.9 which when we select cpu-cpuminer or AMD-sgminer  it says for each that an update is found click ok to download then fails to download anything.  Getting discouraged with trying to mine vertcoin.

**Comment by zemrys** [comment]
This is likely due to your security software(s) preventing the automated download and extraction of the miner software.  This is a common issue that can be solved by making an exception for the OCM in your security software such as Windows Defender.  This is a very common problem for all mining software in the industry.  More info can be found [here](https://github.com/vertcoin-project/One-Click-Miner/issues/8).

**Comment by sohosynergy** [comment]
I wish that were the case but I have not only disabled the Windows Defender for testing but also added the miner as an exception. I also have the windows firewall disabled and no other third party security software as it would interfere with the mining.  I tested with xmrig for the other coins I mine and the cpu and gpu miners are working fine.  I can say it is something to do with your application.  Any suggestions will help.  Looks like a problem report as issue #83 and #85 are the same as I have.

**Comment by zemrys** [comment]
Please try the most recent update found [HERE](https://github.com/vertcoin-project/One-Click-Miner/releases/tag/1.1.8.0). This includes a fix for the issues mentioned.  GitHub implemented new security measures recently that broke the OCM's download functionality.

**Comment by sohosynergy** [comment]
The cpu miner works but AMD miner opens for a half second and shuts down...it does this in an endless loop.
