### ISSUE TITLE
opm_cpuminer contains a virus

### ISSUE THREAD

**Issue by Mayurbora90** [vertcoin/One-Click-Miner#88]
I am trying to start one click miner for Vertcoin and while downloading miner files Kaspersky antivirus is detecting a virus each time i restart and proceed with download.

Is there really a virus? If not what can be done?

**Comment by KJee85** [comment]
Some antivirus have started flagging exe's with miner in the name because of the prevalence of malware/viruses with do maliciously mine coins on your computer.

The miner in this case is from Vertcoin and is something you are in control over. You can add an exception to Kaspersky for this exe.

If you want to "triple check" as it were feel free to ensure the location is one where you have installed the One Click Miner as well as validate the hashes for the release that you used from https://github.com/vertcoin-project/One-Click-Miner/releases

**Comment by zemrys** [comment]
CPU mining is no longer supported by the OCM.
