### ISSUE TITLE
Configurable Miner/Pool install location 

### ISSUE THREAD

**Issue by falconmick** [vertcoin/One-Click-Miner#9]
Hey guys, I have a tiny C drive and large other drives, so I typically attempt to not install to it. However the one click miner downloads the sub-components to Documents. This is causing people with certain limitations on their user accounts issues (https://www.reddit.com/r/vertcoin/comments/77j4jy/i_keep_getting_this_when_trying_to_run_the/).

Wouldn't it just make more sense to just install to program files under a sub-folder of the 1 click miner? Config would be awesome, but I can understand that there are only 24 hrs in a day.

Thoughts?

**Comment by zemrys** [comment]
The OCM itself is only ~1MB, and the downloaded miners will only take up to ~100MB **if** you have all of them installed.  Also, the OCM is designed to automate the mining process for beginners, which is why everything is stored in My Documents. It's the only dedicated location that's easily found by novice users with open permissions that doesn't potentially force the need for administrative rights.

**Comment by patchandthat** [comment]
I agree that this ought to be configurable, while still being able to be ignored by a novice.

I'm happy to pick this up as it's relatively close to what I'm doing at the moment.

**Comment by o-Epictetus-o** [comment]
Yes PLEASE! Would love to have everything in one folder.

**Comment by zemrys** [comment]
Being implemented in next release.
