### ISSUE TITLE
Crashing and failure?

### ISSUE THREAD

**Issue by jar404541** [vertcoin/One-Click-Miner#91]
Hey, so I've been mining vertcoin for a few months now without issue... I recently upgraded my system, (2 hydrocopper OC 1080 ti and an i9) and I am not sure when the problems started, but for the past week I've been having issues. I can mine fine with just one card, but when I do 2, it works for a while, then the screen turns off and back on, default sound is set to my monitor, and I get an error message that says unspecified launch failure. I have a custom liquid cooling loop, so the cards don't get above 60 degrees, I am also on a climate controlled room, I've tried installing old Nvidia drivers, old vertcoin ocm, old vertcoin core, and also I'm running my own node and am mining off of that. So help? If you need any clarification let me know!

**Comment by jar404541** [comment]
It is also giving me the error for both gpus, the launch timed out and was terminated

**Comment by zemrys** [comment]
I apologize for the delay.  This is likely due to drawing more current than your PSU can safely output, or you may have incompatible overclock settings applied that are causing your cards to crash.  I would recommend starting with OC if that applies, if not make sure your PSU is rated at LEAST 10% greater than your current load.
